
    <h1><?php echo $this->titulo; ?></h1>
	<p><a href="<?php echo $this->url(array('controller' => 'establecimiento', 'action' => 'add')) ; ?>">Agregar nuevo Establecimiento</a></p>
	<table>
	    <tr>
		    <td>Nombre del hotel</td>
		    <td>Ubicacion</td>
		    <td>Tipo de Establecimiento</td>
		    <td>Fecha de Inaguracion</td>
		    <td>Usuario</td>
			<td>Opcion</td>
		</tr>
		<?php foreach($this->hotel as $hotels) :?>
		<tr>
		    <td><?php echo $this->escape($hotels['nombre_h']);?></td>
		    <td><?php echo $this->escape($hotels['ubicacion']);?></td>
		    <td><?php echo $this->escape($hotels['tipo_h']);?></td>
		    <td><?php echo $this->escape($hotels['fecha_i']);?></td>
		    <td><?php echo $this->escape($hotels['nombre'].' '.$hotels['apellido']);?></td>
		    <td>
			   <a href="<?php echo $this->url(array('controller' => 'habitacion', 'action' => 'tipo', 'id' => $hotels['id_h'])); ?>">Ver Habitaciones</a>
			   /
			   <a href="<?php echo $this->url(array('controller' => 'habitacion', 'action' => 'add', 'id' => $hotels['id_h'])); ?>">Agregar Habitacion</a>
			   /
			   <a href="<?php echo $this->url(array('controller' => 'establecimiento', 'action' => 'delete', 'id' => $hotels['id_h'])); ?>">Eliminar</a>
			   / 
			   <a href="<?php echo $this->url(array('controller' => 'establecimiento', 'action' => 'put', 'id' => $hotels['id_h'])); ?>">Modificar</a>
			 </td>
		</tr>
		<?php endforeach; ?>
	</table>
