<html>
<head>
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
</head>
<body>
    <h1><?php echo $this->titulo; ?></h1>
	<table>
	    <tr>
		    <td>Genero</td>
		    <td>Descripcion</td>
		</tr>
		<?php foreach($this->tips as $tp) : ?>
		<tr>
		    <td><?php echo $this->escape($tp->genero);?></td>
		    <td><?php echo $this->escape($tp->descripcion);?></td>
		</tr>
		<?php endforeach; ?>
	</table>
</body>
</html>