
    <h1><?php echo $this->titulo; ?></h1>
	<p><a href="<?php echo $this->url(array('controller' => 'usuarioh', 'action' => 'add')) ; ?>">Agregar nuevo usuario</a></p>
	<table>
	    <tr>
		    <td>Nombre</td>
		    <td>Apellido</td>
		    <td>Fecha de Nacimiento</td>
		    <td>Correo</td>
			<td>Opcion</td>
		</tr>
		<?php foreach($this->usuario as $users) : ?>
		<tr>
		    <td><?php echo $this->escape($users->nombre);?></td>
		    <td><?php echo $this->escape($users->apellido);?></td>
		    <td><?php echo $this->escape($users->fecha_nac);?></td>
		    <td><?php echo $this->escape($users->correo);?></td>
		    <td>
			   <a href="<?php echo $this->url(array('controller' => 'usuarioh', 'action' => 'delete', 'id' => $users->id_u)); ?>">Eliminar</a>
			   / 
			   <a href="<?php echo $this->url(array('controller' => 'usuarioh', 'action' => 'put', 'id' => $users->id_u)); ?>">Modificar</a>
			 </td>
		</tr>
		<?php endforeach; ?>
	</table>
